"""Trace reason-code constants."""

TRACE_DISABLED = "TRACE_DISABLED"
TRACE_FAIL_OPEN = "TRACE_FAIL_OPEN"
NO_PRIMARY_ELIGIBLE_CANDIDATE = "NO_PRIMARY_ELIGIBLE_CANDIDATE"
RESOLVER_UNRESOLVED = "RESOLVER_UNRESOLVED"
SUBMISSION_GATE_BLOCKED = "SUBMISSION_GATE_BLOCKED"
BACKEND_REJECTED = "BACKEND_REJECTED"
